security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        App\BackBundle\Entity\Admin: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER


    providers:
        chain_providers: [in_memory,user_db]
        in_memory:
            memory:
                users:
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

        user_db:
                entity: { class: AppBackBundle:Admin, property: username }
    firewalls:
        main:
            pattern:    /.*
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /
            logout:
                path: logout
                target: /
            security: true
            anonymous: true

            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
            - { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: /admin, roles: ROLE_ADMIN }
            - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
