App\BackBundle\Entity\Adherent:
    type: entity
    table: adherent
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        prenom:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        email:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        dateNaissance:
            type: date
            nullable: true
            comment: ''
            column: date_naissance
        dateAdhesion:
            type: date
            nullable: true
            comment: ''
            column: date_adhesion
        photo:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        paiment:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
