App\BackBundle\Entity\Facture:
    type: entity
    table: facture
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        reference:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        objet:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        date:
            type: date
            nullable: true
            comment: ''
        somme:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        type:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        file:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
